### ISSUE TITLE
Feature Request: mipsrop Update to IDA 6.7+ API

### ISSUE THREAD

**Issue by decidedlygray** [tacnetsol/ida#12]
I will hopefully learn enough to submit a PR on this, but I wanted to open this issue to request `ida/plugins/mipsrop/mipsrop.py` be upgraded to the IDA 6.7+ Actions API.

Details, including code samples on what needs to be added, can be found here: http://www.hexblog.com/?p=886 There is also an open PR for a similar refactoring for a different plugin.

Basically, since IDA 6.7 onward, plugins are supposed to use the Actions API instead of the old menu APIs. Starting with IDA 7.0 onward, these old APIs have been completely removed. Anyone trying to use IDA 7.0+ will receive 2 errors when starting up IDA and trying to use `mipsrop.py`:
```
Failed while executing plugin_t.init():
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins/mipsrop.py", line 703, in init
    self.menu_context = idaapi.add_menu_item("Search/", "mips rop gadgets", "", 0, self.run, (None,))
AttributeError: 'module' object has no attribute 'add_menu_item'
```
And:
```
Failed while executing plugin_t.term():
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins/mipsrop.py", line 707, in term
    idaapi.del_menu_item(self.menu_context)
AttributeError: 'module' object has no attribute 'del_menu_item'
```

Cheers!

**Comment by fuzzywalls** [comment]
Fixed in commit #23
