### ISSUE TITLE
LocalXrefs

### ISSUE THREAD

**Issue by maskelihileci** [tacnetsol/ida#41]
IDA PRO 7.5
Windows 10 1607
Python 3.8

Traceback (most recent call last):
  File "C:/IDA Pro 7.5/plugins/localxrefs.py", line 198, in activate
    show_local_xrefs()
  File "C:/IDA Pro 7.5/plugins/localxrefs.py", line 167, in show_local_xrefs
    r = LocalXrefs()
  File "C:/IDA Pro 7.5/plugins/localxrefs.py", line 64, in __init__
    self._profile_function()
  File "C:/IDA Pro 7.5/plugins/localxrefs.py", line 77, in _profile_function
    self.highlighted = ida_shims.get_highlighted_identifier()
  File "C:/IDA Pro 7.5/plugins\shims\ida_shims.py", line 723, in get_highlighted_identifier
    return fn()
  File "C:\IDA Pro 7.5\python\3\ida_kernwin.py", line 201, in get_highlight
    return _ida_kernwin.get_highlight(*args)
TypeError: get_highlight() takes exactly one argument (0 given)

**Comment by maskelihileci** [comment]
x86-x64 Assembly Does it work on its architecture?

**Comment by fuzzywalls** [comment]
The error you are seeing is because localxrefs expects text to be highlighted in the "IDA View" window. I changed the exception to be more verbose, "No text was highlighted. Nothing to show". 

I don't have a Windows machine to verify, but I ran it against a 64bit executable and it worked fine.

**Comment by maskelihileci** [comment]
I choose it that surprises me, I get the same mistake again

![image](https://user-images.githubusercontent.com/41159853/109718188-10252200-7bb8-11eb-9352-21bec19062cf.png)

**Comment by fuzzywalls** [comment]
You need to highlight a specific element in the line rather than the whole line. From your screenshot, you could select "mov", "eax", "24h", or "edx" to search for references to that particular element in the function. There is an example of highlighting an element in the screenshot below. 

<img width="594" alt="Screen Shot 2021-03-02 at 4 43 46 PM" src="https://user-images.githubusercontent.com/39141855/109719340-81dc7c00-7b76-11eb-9814-f4b4cef8e8d9.png">

**Comment by maskelihileci** [comment]
![image](https://user-images.githubusercontent.com/41159853/109720791-968f3300-7bbb-11eb-944b-d5709516b310.png)

![image](https://user-images.githubusercontent.com/41159853/109720875-b0c91100-7bbb-11eb-8e34-e539342ed06c.png)

![image](https://user-images.githubusercontent.com/41159853/109720945-cc341c00-7bbb-11eb-86dc-98f2ecf23540.png)

![image](https://user-images.githubusercontent.com/41159853/109721027-e241dc80-7bbb-11eb-8776-c0be843caab4.png)

![image](https://user-images.githubusercontent.com/41159853/109721156-0a314000-7bbc-11eb-821d-5f85b92af223.png)


Really tried everything to choose and didn't leave it with one try

**Comment by fuzzywalls** [comment]
Are you highlighting it by clicking on it or click and drag? A simple click will highlight it in IDA's eyes while a click and drag  does not register to it. 

Highlighted through a simple click, this one works:
<img width="179" alt="Screen Shot 2021-03-02 at 5 22 06 PM" src="https://user-images.githubusercontent.com/39141855/109723356-fb2a9d80-7b7b-11eb-8322-fcef5fa027b1.png">


Highlighted through click and drag, this one throws and exception:
<img width="183" alt="Screen Shot 2021-03-02 at 5 22 18 PM" src="https://user-images.githubusercontent.com/39141855/109723379-0251ab80-7b7c-11eb-9ee9-d7cabf95b901.png">

**Comment by fuzzywalls** [comment]
Notice in this image when I click on "ecx" it highlights all other instances of it in the function. I notice in your screenshots the other instances of "ebp" are not highlighted. 
<img width="333" alt="Screen Shot 2021-03-02 at 5 25 54 PM" src="https://user-images.githubusercontent.com/39141855/109723644-5fe5f800-7b7c-11eb-9195-1c0ce4466cf1.png">

**Comment by maskelihileci** [comment]
Really interesting for me the highlighting feature is not working

https://www.hex-rays.com/products/ida/support/idadoc/1386.shtml

Single click does not mark registers in graphics mode as indicated on this page

**Comment by fuzzywalls** [comment]
The last line of your link mentioned ways to enable/disable that feature. Is yours turned off? I turned it off in my IDA installation and I couldn't get the script to work.

**Comment by fuzzywalls** [comment]
This was the option under Options->General->Browser
<img width="289" alt="Screen Shot 2021-03-02 at 6 15 34 PM" src="https://user-images.githubusercontent.com/39141855/109727949-4ac09780-7b83-11eb-8f4c-6799fcade819.png">

**Comment by maskelihileci** [comment]
Thanks. Auto highlight the current identifier feature is turned off, I didn't notice it

Issue now resolved make a note about it so other users don't experience similar error
At least users as stupid as me :)

**Comment by fuzzywalls** [comment]
No problem, glad we could get it all figured out.
