### ISSUE TITLE
ida7.5 plugin start fail

### ISSUE THREAD

**Issue by 1094093288** [tacnetsol/ida#43]
After putting misrop.py in the plugins directory and restarting in the ida7.5 version, the search does not show the plugins. What is going on?

**Comment by 1094093288** [comment]
Python>mipsrop.find()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'mipsrop' has no attribute 'find'

**Comment by fuzzywalls** [comment]
In case this issue shows up for others, what was your solution?

**Comment by 1094093288** [comment]
Sorry, shims are missing, just put shims in the plugins directory and you can use it




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Evan ***@***.***&gt;; 
发送时间: 2021年5月14日(星期五) 晚上8:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [tacnetsol/ida] ida7.5 plugin start fail (#43)






如果这个问题出现在其他人身上，你的解决方案是什么？

—
因为修改了打开/关闭状态，所以您收到了此消息。
直接回复此邮件，在GitHub上查看或者取消订阅.

**Comment by fuzzywalls** [comment]
Ah, ok. It sounds like you did a manual copy instead of running the `install.py` script. It should be fine, but if you run into more problems you should try that. Thanks for letting me know and glad you got it working.
