### ISSUE TITLE
ida_shims.py: undefined function PLUGIN_ENTRY

### ISSUE THREAD

**Issue by pureGavin** [tacnetsol/ida#45]
![image](https://user-images.githubusercontent.com/45478229/120457346-f4a10180-c3c8-11eb-8b41-ad5242f44078.png)
after i copy the plugin py file and start IDA pro, this message box just show up, what should i do?

**Comment by fuzzywalls** [comment]
The plug-ins should be installed with the provided install script instead of a manual copy. This error is seen because the installer will place that file in a directory called shims, which prevents Ida from treating it like a plug-in and popping that error.

**Comment by fuzzywalls** [comment]
The .cisco file it is failing to copy is not part of our repo. Might be worth checking out a fresh repo and trying again or removing the .cisco directory/file.

**Comment by fuzzywalls** [comment]
Yes, it works for me. Are you showing hidden files and directories as well?

**Comment by fuzzywalls** [comment]
@pureGavin I updated the install script to not die when it encounters files/directories it doesn't expect. Can you update and give it a try?

**Comment by pureGavin** [comment]
> @pureGavin I updated the install script to not die when it encounters files/directories it doesn't expect. Can you update and give it a try?

only try IDA7.5 and IDA6.8;  it's work for IDA6.8 but not for IDA7.5

**Comment by pureGavin** [comment]
> @pureGavin I updated the install script to not die when it encounters files/directories it doesn't expect. Can you update and give it a try?

do you have any plan about mipsrop for IDA7.5?

**Comment by fuzzywalls** [comment]
Thats weird....we have IDA7.5 and it works. We are on Linux and based on your file paths I assume you're on Windows. What type of failures are you seeing?

**Comment by pureGavin** [comment]
![image](https://user-images.githubusercontent.com/45478229/120465356-76485d80-c3d0-11eb-8da5-be2fa0669bf0.png)
this show up when i execute mipsrop.py, and nothing show up when i execute ida_shims.py

**Comment by pureGavin** [comment]
> Thats weird....we have IDA7.5 and it works. We are on Linux and based on your file paths I assume you're on Windows. What type of failures are you seeing?

should i send you my IDA7.5 cause it's  windows version, and i pay nothing to hexray :p

**Comment by fuzzywalls** [comment]
Haha no thanks, I try to avoid Windows as much as possible. I think your failures are from a previously broken install. The directory structure in the plugins directory should be filled with a bunch of .so files for me probably .lib for you and the python plugins. There should be a shims directory in there as well which should contain ida_shims.py and an __init__.py file. Add the __init__.py if it doesnt exist, its an empty file, and remove any extra ida_shims.py files that aren't in the shims file. You can also try to run the install script with the -d flag to uninstall the plugins and then try reinstalling. Also, if you didnt run the installer against both IDA installations you'll need to do that as well.
